# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.head_ref }}-lint
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

